Goliath/Goliath/Controllers/UserPanelController.cs
using Goliath.Attributes;
using Goliath.Enums;
using Goliath.Helper;
using Goliath.Models;
using Goliath.Models.Accounts;
using Goliath.Repository;
using Goliath.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Goliath.Controllers
{
    /// <summary>
    /// Manages the views for the User Panel which repersents the data that can be manipulated by a
    /// registered user.
    /// </summary>
    public sealed class UserPanelController : Controller
    {
        private readonly ILogger _logger;
        private readonly IAccountRepository _accountRepository;
        private readonly ISmsVerifyTokensRepository _requestTable;
        private readonly IUserTimeoutsRepository _timeouts;
        private readonly IGoliathCaptchaService _captcha;
        private readonly ICookieManager _cookies;

        public UserPanelController(IAccountRepository accountRepository, IGoliathCaptchaService captcha, ISmsVerifyTokensRepository requestTable, ICookieManager cookies, IUserTimeoutsRepository timeouts, ILogger<AuthController> logger)
        {
            _accountRepository = accountRepository;
            _captcha = captcha;
            _requestTable = requestTable;
            _cookies = cookies;
            _logger = logger;
            _timeouts = timeouts;
        }

        [HttpPost]
        [Route("userpanel/authorize")]
        public IActionResult NotAuthenticated(string title)
        {
            return View(new NotAuthorizedModel()
            {
                Title = title
            });
        }

        [Route("userpanel/authorize")]
        [HttpGet]
        public IActionResult NotAuthenticated(NotAuthorizedModel model)
        {
            return View(model);
        }

        [GoliathAuthorize(nameof(Profile))]
        [Route("sms-code-sent")]
        public IActionResult SentSmsCode()
        {
            return View();
        }

        [GoliathAuthorize(nameof(Profile))]
        public IActionResult Index()
        {
            return View(nameof(Profile));
        }

        [GoliathAuthorize(nameof(Profile))]
        public IActionResult Profile()
        {
            return View();
        }

        [GoliathAuthorize(nameof(Profile))]
        [PreventDuplicateRequest]
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Profile(ProfileSettingsModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (!await _captcha.IsCaptchaValidAsync())
            {
                ModelState.AddModelError(_captcha.CaptchaValidationError().Key, _captcha.CaptchaValidationError().Value);
                return View();
            }

            ApplicationUser goliathUser = await _accountRepository.GetUserFromContextAsync(User);

            if (!await _timeouts.CanRequestProfileSettingsUpdateAsync(goliathUser.Id))
            {
                ModelState.AddModelError(string.Empty, "Please wait before updating your profile again.");
                return View();
            }

           #region Simple value updates

            // ** Values which do not need database checking
            goliathUser.BackgroundColor = model.BackgroundColor;
            goliathUser.DarkTheme = model.DarkThemeEnabled;
            goliathUser.LogoutThreshold = int.Parse(model.LogoutThreshold);
            // ** If settings which require a two-factor code are updated.
            bool requiresTwoFactor = false;

            #endregion Simple value updates

            #region Validating email

            if (!string.IsNullOrWhiteSpace(model.NewEmail))
            {
                if (await _accountRepository.DoesEmailExistAsync(model.NewEmail))
                {
                    ModelState.AddModelError(string.Empty, $"The email {model.NewEmail} is currently in use.");
                    return View();
                }
                else
                {
                    goliathUser.UnverifiedNewEmail = model.NewEmail;
                    requiresTwoFactor = true;
                }
            }

            #endregion Validating email

            #region Validating phone number

            if (!string.IsNullOrWhiteSpace(model.NewPhoneNumber))
            {
                if (await _accountRepository.DoesPhoneNumberExistAsync(model.NewPhoneNumber))
                {
                    ModelState.AddModelError(string.Empty, $"The phone number {model.NewPhoneNumber} is currently in use.");
                    return View();
                }
                else
                {
                    goliathUser.UnverifiedNewPhone = model.NewPhoneNumber;
                    requiresTwoFactor = true;
                }
            }

            #endregion Validating phone number

            #region Validating password

            if (!string.IsNullOrWhiteSpace(model.NewPassword))
            {
                if (await _accountRepository.IsPasswordValidAsync(goliathUser, model.NewPassword))
                {
                    ModelState.AddModelError(string.Empty, "Your new password must be different then your previous password.");
                    return View();
                }
                IdentityResult result = await _accountRepository.UpdatePasswordAsync(goliathUser, model.CurrentPassword, model.NewPassword);
                if (!result.Succeeded)
                {
                    _captcha.DeleteCaptchaCookie();
                    ModelState.AddModelError(string.Empty, "Your entry in \"Current Password\" does not match your current password.");
                    return View();
                }
                goliathUser.LastPasswordUpdate = DateTime.UtcNow.ToString();
                requiresTwoFactor = true;
            }

            #endregion Validating password

            #region Check two-factor codes

            if (goliathUser.TwoFactorEnabled && requiresTwoFactor)
            {
                if (string.IsNullOrWhiteSpace(model.TwoFactorCode))
                {
                    _captcha.DeleteCaptchaCookie();
                    ModelState.AddModelError(string.Empty, "Your two-factor code is invalid.");
                    return View();
                }
                if (!await _accountRepository.TwoFactorCodeValidAsync(goliathUser, model.TwoFactorCode))
                {
                    _captcha.DeleteCaptchaCookie();
                    ModelState.AddModelError(string.Empty, "Your two-factor code is invalid.");
                    return View();
                }
            }

            #endregion Check two-factor codes

            #region Sending potential verification emails

            // If all of the user settings are correct then check if we need to send messages to
            // update phone/email.
            if (!string.IsNullOrWhiteSpace(model.NewEmail))
            {
                await _accountRepository.GenerateNewEmailConfirmationTokenAsync(goliathUser, new DeviceParser(GetClientUserAgent(), GetRemoteClientIPv4()));
            }
            if (!string.IsNullOrWhiteSpace(model.NewPhoneNumber))
            {
                await _accountRepository.GenerateNewPhoneConfirmationTokenAsync(goliathUser, new DeviceParser(GetClientUserAgent(), GetRemoteClientIPv4()));
            }

            #endregion Sending potential verification emails

            #region Updating/Caching
            // Update all of the changed values.
            await _accountRepository.UpdateUserAsync(goliathUser);
            await _captcha.CacheNewCaptchaValidateAsync();
            await _timeouts.UpdateRequestAsync(goliathUser.Id, UserRequest.UpdateProfileSettings);
            #endregion Updating/Caching

            ModelState.Clear();
            _logger.LogInformation($"{goliathUser.Id} ({goliathUser.UserName}) - Updated profile settings successfully.");
            TempData[TempDataKeys.Redirect] = RedirectPurpose.SettingsUpdatedSuccess;
            return View();
        }

        [GoliathAuthorize(nameof(Profile))]
        [Route("userpanel/verify-phone")]
        public IActionResult ConfirmPhoneNumber()
        {
            return View();
        }

        [GoliathAuthorize(nameof(Profile))]
        [Route("userpanel/verify-phone")]
        [PreventDuplicateRequest]
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmPhoneNumber(VerifyPhoneNumberModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.Clear();
                return View();
            }

            #region Validate token data type & captcha

            if (!int.TryParse(model.Token, out _))
            {
                ModelState.AddModelError(string.Empty, "Token must be a number.");
                return View();
            }

            if (!await _captcha.IsCaptchaValidAsync())
            {
                ModelState.AddModelError(_captcha.CaptchaValidationError().Key, _captcha.CaptchaValidationError().Value);
                return View();
            }

            #endregion Validate token data type & captcha

            ApplicationUser user = await _accountRepository.GetUserFromContextAsync(User);

            #region Validating password & ensuring token validity

            if (!await _accountRepository.IsPasswordValidAsync(user, model.Password))
            {
                _captcha.DeleteCaptchaCookie();
                ModelState.AddModelError(string.Empty, "Incorrect Password.");
                return View();
            }

            if ((await _accountRepository.ConfirmPhoneAsync(user, model.Token)).Succeeded)
            {
                model.IsCompleted = true;
                user.UnverifiedNewPhone = string.Empty;
                await _captcha.CacheNewCaptchaValidateAsync();

Goliath/Goliath/Views/Shared/Layouts/_AuthenticationPanel.cshtml
@using Goliath.Models;
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> _signInManager;
@*
    Layout for Authentication Panel.
    - Logins
    - Registering
    - Forgot Password
    - Login with OAuth
    - Verify Email
    - Etc.
*@

@{
    Layout = "_Layout";
}
@* Specific to _AuthenticationPanel. *@
@section UniqueHeader {
    <link type="text/css" href="https://unpkg.com/aos@next/dist/aos.css" asp-append-version="true" />
    <link href="~/css/Auth/LoginStyle.css" rel="stylesheet" asp-append-version="true" />
    <script src="~/js/Auth/AuthenticationScript.js" asp-append-version="true"></script>
}

@*If the user is logged in then redirect them to userpanel.*@
@if (_signInManager.IsSignedIn(User))
{
    Context.Response.Redirect(Url.Action("Index", "UserPanel"));

}

<section id="center-banner" style="position: absolute;">
    <!-- Dynamic Current Notifications -->
</section>
@*Center Content*@
<main id="outer">
    <section id="inner" class="container parent-container">
        <div class="row">

            <!-- Carousel Half -->
            <article class="col-md d-none d-md-flex bg-dark round-left" id="left-container">

                <div class="container h-100">
                    <div class="row align-items-center h-100">

                        <div class="col-12 mx-auto">
                            <article id="carouselExampleControls" class="carousel slide h-100" data-ride="carousel">
                                <ol class="carousel-indicators" style="padding-bottom: 2rem;">
                                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                                </ol>

                                <div class="carousel-inner" role="listbox">
                                    <div class="carousel-item active">
                                        <img class="d-block img-fluid round" src="@ViewData["CarouselImage1"]" alt="First slide">
                                    </div>
                                    <div class="carousel-item">
                                        <img class="d-block img-fluid round" src="@ViewData["CarouselImage2"]" alt="Second slide">
                                    </div>
                                    <div class="carousel-item">
                                        <img class="d-block img-fluid round" src="@ViewData["CarouselImage3"]" alt="Third slide">
                                    </div>
                                </div>
                                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </article>
                        </div>
                    </div>
                </div>
            </article>

            <!-- The content half -->
            <article class="col-md-6 round-right" id="right-container">
                <!--<div class="container bg-light round parent-container" style="min-height: 100%;zoom: 1.15; margin-top: 3%" id="right-container">-->
                <div class="d-flex align-items-center py-5">

                    <!-- Header content-->
                    <div class="container-fluid">
                        <div class="row justify-content-md-center">
                            <div class="col-lg-10 col-xl-9 mx-auto">

                                <header class="text-center">
                                    <!-- Top Radio Buttons -->
                                    <div class=" ht-tm-element btn-group btn-group-toggle" data-toggle="buttons">

                                        <a asp-controller="@GoliathControllers.AuthController" asp-action="@nameof(AuthController.Index)" class="btn btn-outline-primary">

                                            <input type="radio" name="options" id="login-radio-btn" autocomplete="off">
                                            Login
                                        </a>
                                        <a asp-controller="@GoliathControllers.AuthController" asp-action="@nameof(AuthController.RegisterMethod)" class="btn btn-outline-primary">

                                            <input type="radio" name="options" id="register-radio-btn" autocomplete="off">
                                            Register
                                        </a>
                                        <div class="btn-group btn btn-outline-primary" id="other-head">
                                            <a id="other-dropdown" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <input type="radio" name="options" id="other-radio-btn" autocomplete="off">
                                                Other
                                            </a>
                                            <!-- Other Drop Down Start -->
                                            <div class="dropdown-menu drop-down" aria-labelledby="other-dropdown" x-placement="bottom-start" id="dropdown">
                                                <a asp-controller="@GoliathControllers.AuthController" asp-action="@nameof(AuthController.ForgotUsername)" id="forgot-username" class="dropdown-item">Forgot Username</a>
                                                <a asp-controller="@GoliathControllers.AuthController" asp-action="@nameof(AuthController.ForgotPassword)" id="forgot-password" class="dropdown-item">Forgot Password</a>
                                                <a asp-controller="@GoliathControllers.AuthController" asp-action="@nameof(AuthController.VerifyEmail)" id="verify-email" class="dropdown-item">Verify Email</a>
                                                <a asp-controller="@GoliathControllers.AesController" asp-action="@nameof(GoliathAesController.Index)" id="verify-email" class="dropdown-item">AES Tools</a>
                                                <div id="dropdown-divider" class="dropdown-divider"></div>
                                                @*OAuth Login Methods*@
                                                <a class="dropdown-item py-xl-1" href="#!"><i id="signin-google-icon" class="fab fa-google px-sm-2 dropdown-bottom-icons"></i>Sign in with Google</a>
                                                <a class="dropdown-item" href="/idk"><i id="signin-ms-icon" class="fab fa-microsoft px-sm-2 dropdown-bottom-icons"></i>Sign in with Microsoft</a>
                                                <a class="dropdown-item" href="/idk"><i id="signin-fb-icon" class="fab fa-facebook-square px-sm-2 dropdown-bottom-icons"></i>Sign in with Facebook</a>
                                                <a asp-controller="@GoliathControllers.RedirectController"
                                                   asp-action="@nameof(RedirectController.Index)"
                                                   asp-route-redirectUrl="https://github.com/jluvisi2021/Goliath"
                                                   asp-route-returnUrl="@Context.Request.Path"
                                                   class="dropdown-item" target="_blank"><i id="dd-git-icon" class="fab fa-github px-sm-2 dropdown-bottom-icons"></i>View GitHub</a>
                                            </div>
                                            <!-- Other Drop Down End -->
                                        </div>
                                    </div>
                                    <!-- Radio Buttons End -->
                                    <hr />
                                    <div>
                                        <!-- Right Panel Header -->
                                        @RenderSection("RightContainerHeader", false)
                                        <!-- Right Panel Header End -->
                                    </div>
                                </header>

                                <div>
                                    <!-- Right Panel Body -->
                                    @RenderBody()
                                    <!-- Right Panel Body End -->
                                </div>
                            </div>
                        </div>
                    </div><!-- End -->
                </div>
            </article><!-- End -->
        </div>
    </section>
</main>

@section Scripts {
    <script type="text/javascript">
            @*Highlight individual button elements depending on the current page*@
        AuthScript.loadButtonElements("@ViewData["ButtonID"]");
        AuthScript.changeTheme();
    </script>
    <script src="https://unpkg.com/aos@next/dist/aos.js" integrity="sha384-ZGo5k5ISlEzWLoXyt+lnvKt9j03Z7GkxXh14zLqVy098XJhcdKHjL8pQYVMI8WiH" crossorigin="anonymous" asp-append-version="true"></script>
    <script>AOS.init();</script>
}

Goliath/Goliath/Views/Shared/Layouts/_UserPanel.cshtml
@*
    Layout for User Panel.
    - Profile
    - Database
    - Tools
    - Help
    - About Goliath
    - Build Info
*@
@using Goliath.Models
@inject Goliath.Repository.IAccountRepository _accountRepository
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> _signInManager
@{
    Layout = "_Layout";
}

@section UniqueHeader {
    <link href="~/css/UserPanel/UserPanelStyle.css" rel="stylesheet" asp-append-version="true" />
    <script src="~/js/UserPanel/UserPanelScript.js" asp-append-version="true"></script>
}

<main>
    <!-- Navbar Start -->
    <header>
        <nav id="top-nav" class="navbar navbar-expand-lg navbar-dark bg-primary ht-tm-element">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <i class="navbar-toggler-icon"></i>
            </button>
            <!-- Navbar Icon Start -->
            <a class="navbar-brand" asp-controller="@GoliathControllers.HomeController" asp-action="@nameof(HomeController.Index)">
                <i class="fas fa-shield-alt"></i>
                Goliath
            </a>
            <!-- Navbar Icon End -->
            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav mr-auto mt-2 mt-md-0">
                    <li class="nav-item" id="profile-nav">
                        <a class="nav-link" asp-controller="@GoliathControllers.UserPanelController" asp-action="@nameof(UserPanelController.Index)">Profile</a>
                    </li>
                    <li class="nav-item" id="database-nav">
                        <a class="nav-link" asp-controller="@GoliathControllers.UserPanelController" asp-action="@nameof(UserPanelController.Database)">Database</a>
                    </li>
                    <li class="nav-item" id="utilities-nav">
                        <a class="nav-link" asp-controller="@GoliathControllers.UserPanelController" asp-action="@nameof(UserPanelController.Utilities)">Utilities</a>
                    </li>
                    <li class="nav-item" id="help-nav">
                        <a class="nav-link" asp-controller="@GoliathControllers.UserPanelController" asp-action="@nameof(UserPanelController.Help)">Help (FAQ)</a>
                    </li>
                    <li class="nav-item" id="about-nav">
                        <a class="nav-link" asp-controller="@GoliathControllers.UserPanelController" asp-action="@nameof(UserPanelController.About)">About Goliath</a>
                    </li>
                    <li class="nav-item" id="build-nav">
                        <a class="nav-link" asp-controller="@GoliathControllers.UserPanelController" asp-action="@nameof(UserPanelController.BuildInfo)">Build Info</a>
                    </li>
                    @*If the user is signed in and is an admin then load admin tab.*@
                    @if (_signInManager.IsSignedIn(User) && await _accountRepository.IsAdminAsync(User.Identity.Name))
                    {
                        <li class="nav-item" id="admin-nav">
                            <a class="nav-link" asp-controller="@GoliathControllers.AdminPanelController" asp-action="@nameof(AdminPanelController.Index)">Admin Panel</a>
                        </li>
                    }

                    @*Dropdown Menu. These do not contain individual pages (Use redirections).*@
                    <li class="nav-item dropdown" id="other-nav">
                        <a class="nav-link dropdown-toggle" href="#" role="button" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Other
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a asp-controller="@GoliathControllers.RedirectController"
                               asp-action="@nameof(RedirectController.Index)"
                               asp-route-redirectUrl="https://github.com/jluvisi2021/Goliath"
                               asp-route-returnUrl="@Context.Request.Path"
                               class="dropdown-item">Go to GitHub</a>

                            <a asp-controller="@GoliathControllers.RedirectController"
                               asp-action="@nameof(RedirectController.Index)"
                               asp-route-redirectUrl="https://github.com/jluvisi2021/Goliath/wiki"
                               asp-route-returnUrl="@Context.Request.Path"
                               class="dropdown-item">Go to Wiki</a>
                            <a asp-controller="@GoliathControllers.RedirectController"
                               asp-action="@nameof(RedirectController.Index)"
                               asp-route-redirectUrl="#!"
                               asp-route-returnUrl="@Context.Request.Path"
                               class="dropdown-item">Suggest Feature</a>
                            <a asp-controller="@GoliathControllers.RedirectController"
                               asp-action="@nameof(RedirectController.Index)"
                               asp-route-redirectUrl="https://github.com/jluvisi2021/Goliath/issues/new"
                               asp-route-returnUrl="@Context.Request.Path"
                               class="dropdown-item">Report Issue</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#!">Share</a>
                        </div>
                    </li>
                </ul>
                @*Load the top right header indicating the user is logged in.*@
                <partial name="_LoginInfo" />
            </div>
        </nav>
    </header>
    <!-- Navbar End -->
    <section class="text-center">
        <!-- UserPanel Body Start -->
        @RenderBody()
        <!-- UserPanel Body End -->
    </section>
</main>

@section Scripts {
    <script type="text/javascript" defer>
        UserPanelScript.updateNav("@ViewData["Title"].ToString().ToLower().Split(" ")[0]");
    </script>
}